name: Deployment on VPS 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exécution d'un script simple
      run: echo "Le workflow CI est déclenché par un push sur GitHub!"